api_token:
  secret: SecretKeyToGenJWTs

declarative: false
#repositories:
#  - name: 
#    publication-uri:
#    server-address:

# Email related properties
email:
  enabled: false
  password:
  username:
  from:
  smtp:
    host:
    port:
    auth:
    starttls:

# Authentication related properties
app:
  authentication: simple
  simple:
    users:
      - login: einstein
        password: testpassword  
        name: Albert Einstein 
      - login: tesla
        password: testpassword
        name: Nicolas Tesla
      - login: galieleo
        password: testpassword
        name: Galileo Galilei
      - login: newton
        password: testpassword
        name: Isaac Newton
      - login: newbie
        password: testpassword
        name: New User
      - login: doe
        password: testpassword
        name: John Doe 
    default:
      admins:
        - einstein            

# Database related properties
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://oa-rdepot-db:5432/rdepot
  username: rdepot
  password: mysecretpassword

# Hibernate related properties
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
  
# Liquibase related properties
spring:
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
    url: jdbc:postgresql://oa-rdepot-db:5432/rdepot
    user: rdepot
    password: mysecretpassword
    enabled: true