version: '3'
services:
  proxy:
    image: library/nginx:alpine
    container_name: oa-rdepot-proxy
    restart: unless-stopped
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/proxy/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./docker/proxy/logs/:/var/log/nginx/
      - repository:/opt/rdepot/repo/:ro
    ports:
      - ${RDEPOT_PORT}:80
    depends_on:
      - app
      - repo
    networks:
      - oa-rdepot
  ldap:
    build: ./docker/build/ldap
    restart: unless-stopped
    hostname: oa-rdepot-ldap
    container_name: oa-rdepot-ldap
    networks:
      - oa-rdepot
    ports:
      - 8080:8080
      - 389:389
      - 636:636
    environment:
      - LDAP_TLS=false
      - LDAP_ORGANISATION=Test Company
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=testpassword
  db:
    image: library/postgres:alpine
    restart: unless-stopped
    hostname: oa-rdepot-db
    container_name: oa-rdepot-db
    volumes:
      - ./docker/db/rdepot.sql:/docker-entrypoint-initdb.d/rdepot.sql:ro
      - ./docker/db/rdepot_insert.sql:/docker-entrypoint-initdb.d/rdepot_insert.sql:ro
    networks:
      - oa-rdepot
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  app:
    build: ./docker/build/app
    restart: unless-stopped
    hostname: oa-rdepot-app
    container_name: oa-rdepot-app
    volumes:
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro
      - ./src/main/resources/yaml:/opt/rdepot/yaml
    ports:
      - 8001:8001
    networks:
      - oa-rdepot
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/postgres
      - DB_USERNAME=postgres
      - LDAP_URL=ldap://oa-rdepot-ldap:389
      - LDAP_BASEDN=dc=example,dc=org
      - LDAP_USEROU=
      - LDAP_LOGINFIELD=cn
      - LDAP_NAMEFIELD=description
      - LDAP_DEFAULT_ADMINS=admin
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001

  repo:
    build: ./docker/build/repo
    restart: unless-stopped
    hostname: oa-rdepot-repo
    container_name: oa-rdepot-repo
    volumes:
      - ./docker/repo/rdepot-repo.jar:/opt/repo/rdepot-repo.jar:ro
      - repository:/opt/rdepot/
      - ./docker/repo/server/:/opt/rdepot/server/
    networks:
      - oa-rdepot
networks:
  oa-rdepot:
    ipam:
      config:
        - subnet: 192.168.49.0/24
volumes:
  repository:
