version: '3'
services:
  proxy:
    image: library/nginx:alpine
    container_name: oa-rdepot-proxy
    restart: unless-stopped
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/proxy/sites-enabled/rdepot:/etc/nginx/sites-enabled/rdepot:ro
      - logs:/var/log/nginx/
      - repository:/opt/rdepot/repo/:ro
    ports:
      - ${RDEPOT_PORT:-80}:80
    depends_on:
      - app
      - repo
    networks:
      - oa-rdepot
  ldap:
    image: osixia/openldap
    restart: unless-stopped
    hostname: oa-rdepot-ldap
    container_name: oa-rdepot-ldap
    networks:
      - oa-rdepot
    ports:
      - 8080:8080
    environment:
      - LDAP_TLS=false
  db:
    image: library/postgres:alpine
    restart: unless-stopped
    hostname: oa-rdepot-db
    container_name: oa-rdepot-db
    volumes:
      - ./docker/db/rdepot.sql:/docker-entrypoint-initdb.d/rdepot.sql:ro
      - db:/var/lib/postgresql/data/
    networks:
      - oa-rdepot
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  app:
    image: openanalytics/rdepot-app
    restart: unless-stopped
    hostname: oa-rdepot-app
    container_name: oa-rdepot-app
    volumes:
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro
      - app-data:/opt/rdepot/generated/
    ports:
      - 8001:8001
    networks:
      - oa-rdepot
    depends_on:
      - db
      - ldap
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/postgres
      - DB_USERNAME=postgres
      - LDAP_URL=ldap://oa-rdepot-ldap:389
      - LDAP_BASEDN=dc=example,dc=org
      - LDAP_USEROU=
      - LDAP_LOGINFIELD=cn
      - LDAP_NAMEFIELD=description
      - LDAP_DEFAULT_ADMINS=admin
      - JAVA_OPTS
  repo:
    image: openanalytics/rdepot-repo
    restart: unless-stopped
    hostname: oa-rdepot-repo
    container_name: oa-rdepot-repo
    volumes:
      - repository:/opt/rdepot/
    networks:
      - oa-rdepot
networks:
  oa-rdepot:
    ipam:
      config:
        - subnet: 192.168.49.0/24
volumes:
  repository:
  app-data:
  logs:
  db:
