declarative: true
repositories:
  - name: A
    publication-uri: http://localhost/repo/A13
    server-address: http://oa-rdepot-repo:8080/A13
  - name: D
    publication-uri: http://localhost/repo/D
    server-address: http://oa-rdepot-repo:8080/D

api_token:
  secret: SecretKeyToGenJWTs

message:
  source:
    basename: i18n/messages

# Database related properties
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://oa-rdepot-db-declarative:5432/rdepot
  username: rdepot
  password: mysecretpassword

# Hibernate related properties
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false

entitymanager:
  packages:
    to:
      scan: eu.openanalytics.rdepot.model

# Email related properties
email:
  password:
  username:
  from:
  smtp:
    host:
    port:
    auth:
    starttls:

# Package upload related properties
package:
  upload:
    dir: /opt/rdepot

# Repository generation related properties
repository:
  generation:
    dir: /opt/rdepot/generated

#spring.mvc.view.prefix=/WEB-INF/pages/
#spring.mvc.view.suffix=.jsp
spring:
  mvc:
    view:
      suffix: .html
  main:
    allow-bean-definition-overriding: true
    log-startup-info: false  

  output:
    ansi:
      enabled: always    
#spring.devtools.remote.secret=thisismysecret
server:
  error:
    include-stacktrace: always
    path: /error
    
management:
  metrics:
    web:
      server:
        auto-time-requests: false

springdoc:
  pathsToMatch: /api/**
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /docs/api.html
    disable-swagger-default-url: true
    url: /v1/api-docs
    display-query-params: true

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG   

#storage related properties
localStorage:
  maxRequestSize: 10

storage:
  implementation: local

requestTimeout: 10            

#repo:            
      
