app:
  authentication: ldap
  ldap:
    url: ldap://oa-rdepot-ldap:389
    basedn: dc=example,dc=org
    userou: 
    loginfield: cn
    namefield:
      - givenName
      - sn
    emailfield: mail
    default:
      admins: einstein 
