api_token:
  secret: SecretKeyToGenJWTs

declarative: true
repositories:
  - name: A
    publication-uri: http://localhost/repo/A13
    server-address: http://oa-rdepot-repo:8080/A13
  - name: D
    publication-uri: http://localhost/repo/D
    server-address: http://oa-rdepot-repo:8080/D
    mirrors:
      - name: CRAN
        uri: https://cran.r-project.org
        sync-interval: ""
        type: tarball
        generate-manuals: true
        packages:
          - name: ggplot2
            version: 3.3.2
          - name: plotly
            generate-manuals: false
      - name: Bioconductor-3.12
        uri: https://bioconductor.org/packages/3.12/bioc
        sync-interval: ""
        type: tarball
        generate-manuals: false
        packages:
          - name: annotate
            version: 1.68.0
      - name: Bioconductor-release
        uri: https://bioconductor.org/packages/release/bioc
        sync-interval: ""
        type: tarball
        packages:
          - name: genefilter

# Authentication related properties
app:
  authentication: ldap
  ldap:
    url: ldap://oa-rdepot-ldap:389
    basedn: dc=example,dc=org
    userou: 
    loginfield: cn
    namefield:
      - givenName
      - sn
    emailfield: mail
    default:
      admins: einstein       

# Database related properties
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://oa-rdepot-db:5432/declarative
  username: rdepot
  password: mysecretpassword

# Hibernate related properties
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false

# Enable Liquibase
spring:
  liquibase:
    enabled: false

# Debug SQL queries
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
