version: '3'
services:
  proxy:
    image: library/nginx:alpine
    container_name: oa-rdepot-proxy
    restart: always
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/proxy/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - repository:/opt/rdepot/repo/:ro
    ports:
      - 8017:80
    depends_on:
      - app
      - repo
    networks:
      - oa-rdepot
  ldap:
    image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/rdepot-ldap-it:develop
    restart: unless-stopped
    hostname: oa-rdepot-ldap
    container_name: oa-rdepot-ldap
    networks:
      - oa-rdepot
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_TLS=false
      - LDAP_ORGANISATION=Test Company
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=testpassword
  db:
    image: library/postgres:alpine
    restart: always
    hostname: oa-rdepot-db
    container_name: oa-rdepot-db
    volumes:
      - ./docker/db/rdepot.sql:/docker-entrypoint-initdb.d/rdepot.sql:ro
      - ./docker/db/database.sql:/opt/database.sql
      - ./docker/db/dump:/opt/rdepot/
    networks:
      - oa-rdepot
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  app:
    image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/rdepot-app-it:develop
    restart: always
    hostname: oa-rdepot-app
    container_name: oa-rdepot-app
    volumes:
      - ./docker/app/rdepot.war:/opt/rdepot/rdepot.war:ro
      - ./docker/app/rdepot.conf:/opt/rdepot/rdepot.conf:ro
      - ./itestSourceFiles:/opt/testSourceFiles:ro
      - ./itestGenerated:/opt/testGenerated:ro
      - ./itestNewFiles:/opt/newFiles:ro
    ports:
      - 8001:8001
    networks:
      - oa-rdepot
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://oa-rdepot-db:5432/postgres
      - DB_USERNAME=postgres
      - LDAP_URL=ldap://oa-rdepot-ldap:389
      - LDAP_BASEDN=dc=example,dc=org
      - LDAP_USEROU=
      - LDAP_LOGINFIELD=cn
      - LDAP_NAMEFIELD=description
      - LDAP_DEFAULT_ADMINS=admin
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
    healthcheck:
      test: ["CMD-SHELL", "if [ \"$$(curl -I localhost:8080 2>/dev/null | grep HTTP/1.1 | cut -d\" \" -f2)\" != \"302\" ]; then exit 1; else exit 0; fi;"]
      interval: 10s
      timeout: 10s
      retries: 10
  repo:
    image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/rdepot-repo-it:develop
    restart: always
    hostname: oa-rdepot-repo
    container_name: oa-rdepot-repo
    volumes:
      - ./docker/repo/rdepot-repo.jar:/opt/repo/rdepot-repo.jar:ro
      - repository:/opt/rdepot/
      - ./itestServer:/opt/testServer
    networks:
      - oa-rdepot
networks:
  oa-rdepot:
    ipam:
      config:
        - subnet: 192.168.49.0/24
volumes:
  repository:
